export const listings = [
  {
    id: 1,
    name: "Landmark",
    location: "Hà Nội",
    view: "Hướng sông",
    date: "13 - 18 thg 3",
    price: "1.730.000",
    image: "https://source.unsplash.com/400x300/?apartment",
    favorite: false,
  },
  {
    id: 2,
    location: " Quảng Ninh",
    view: "Hướng Bãi biển và biển",
    date: "9 - 14 thg 3",
    price: "931.412",
    image: "https://source.unsplash.com/400x300/?beach-house",
    favorite: true,
  },
  {
    id: 3,
    location: "Tây Hồ, Việt Nam",
    view: "Hướng gần hồ và sông",
    date: "3 thg 3",
    price: "1.600.000",
    image: "https://source.unsplash.com/400x300/?night-apartment",
    favorite: true,
  },
  {
    id: 4,
    location: "Tây Hồ, Việt Nam",
    view: "Cách 7 km",
    date: "4 - 9 thg 5",
    price: "1.750.000",
    image: "https://source.unsplash.com/400x300/?luxury-apartment",
    favorite: true,
  },
  {
    id: 5,
    location: "Đà Lạt",
    view: "Cách 7 km",
    date: "4 - 9 thg 5",
    price: "1.750.000",
    image: "https://source.unsplash.com/400x300/?luxury-apartment",
    favorite: false,
  },
  {
    id: 6,
    location: "Quảng Ninh",
    view: "Cách 7 km",
    date: "4 - 9 thg 5",
    price: "1.750.000",
    image: "https://source.unsplash.com/400x300/?luxury-apartment",
    favorite: true,
  },
  {
    id: 7,
    location: "Đà Nẵng",
    view: "Cách 7 km",
    date: "4 - 9 thg 5",
    price: "1.750.000",
    image: "https://source.unsplash.com/400x300/?luxury-apartment",
    favorite: true,
  },
  {
    id: 8,
    location: "TP. Hồ Chí Minh",
    view: "Cách 7 km",
    date: "4 - 9 thg 5",
    price: "1.750.000",
    image: "https://source.unsplash.com/400x300/?luxury-apartment",
    favorite: true,
  },
];
